import type { InvestorWithThesis, StartupWithData } from "../domain";
import { formatMoney, formatRange } from "../format";
import { matchEngine } from "../match-engine";

/**
 * Insight provider abstraction.
 *
 * Every generative surface in FundMatch (company summary, thesis inference,
 * fit explanation, strengths, risks) goes through this interface. The shipped
 * implementation is deterministic so the pilot works with no model connected.
 * A hosted-model provider can be registered later without touching the UI.
 */

export interface GeneratedInsight<T> {
  value: T;
  provider: string;
  mode: "deterministic" | "model";
  generatedAt: string;
}

export interface InsightProvider {
  readonly id: string;
  readonly mode: "deterministic" | "model";
  companySummary(startup: StartupWithData): GeneratedInsight<string>;
  inferThesis(investor: InvestorWithThesis, recentSectors: string[]): GeneratedInsight<string>;
  whyItFits(startup: StartupWithData, investor: InvestorWithThesis): GeneratedInsight<string>;
  keyStrengths(startup: StartupWithData, investor: InvestorWithThesis): GeneratedInsight<string[]>;
  risks(startup: StartupWithData, investor: InvestorWithThesis): GeneratedInsight<string[]>;
}

function wrap<T>(value: T, provider: DeterministicInsightProvider): GeneratedInsight<T> {
  return { value, provider: provider.id, mode: provider.mode, generatedAt: new Date().toISOString() };
}

export class DeterministicInsightProvider implements InsightProvider {
  readonly id = "deterministic-v1";
  readonly mode = "deterministic" as const;

  companySummary(startup: StartupWithData) {
    if (startup.ai_summary) return wrap(startup.ai_summary, this);
    const arr = startup.metrics.find((m) => m.metric_key === "arr")?.value_display ?? "pre-revenue";
    const growth = startup.metrics.find((m) => m.metric_key === "growth")?.value_display ?? "unreported growth";
    const text = `${startup.name} is a ${startup.stage} ${startup.sector.toLowerCase()} company in ${startup.geography}. ${startup.tagline ?? ""} Current scale is ${arr} with ${growth} year-over-year, raising ${formatMoney(startup.funding_ask ? Number(startup.funding_ask) : null)}.`;
    return wrap(text.replace(/\s+/g, " ").trim(), this);
  }

  inferThesis(investor: InvestorWithThesis, recentSectors: string[]) {
    const t = investor.thesis;
    const sectors = (t?.sectors ?? []).join(", ") || recentSectors.join(", ") || "generalist";
    const stages = (t?.stages ?? []).join(" and ") || "seed";
    const geos = (t?.geographies ?? []).join(", ") || "global";
    const cheque = formatRange(
      t?.check_min ? Number(t.check_min) : null,
      t?.check_max ? Number(t.check_max) : null,
    );
    const text = `${investor.firm_name} concentrates on ${sectors} at ${stages} across ${geos}, writing ${cheque} cheques${
      t?.min_growth_pct ? ` and screening for at least ${Number(t.min_growth_pct)}% YoY growth` : ""
    }.${recentSectors.length ? ` Recent deal-flow signals lean toward ${recentSectors.slice(0, 3).join(", ")}.` : ""}`;
    return wrap(text, this);
  }

  whyItFits(startup: StartupWithData, investor: InvestorWithThesis) {
    return wrap(matchEngine.score(startup, investor).explanation, this);
  }

  keyStrengths(startup: StartupWithData, investor: InvestorWithThesis) {
    const match = matchEngine.score(startup, investor);
    const extras: string[] = [];
    const growth = startup.metrics.find((m) => m.metric_key === "growth");
    if (growth?.value_numeric && Number(growth.value_numeric) >= 100) {
      extras.push(`Growth is compounding fast at ${growth.value_display} YoY`);
    }
    if (startup.team_size && startup.team_size < 20) {
      extras.push(`Lean team of ${startup.team_size} relative to revenue`);
    }
    return wrap([...match.strengths, ...extras].slice(0, 5), this);
  }

  risks(startup: StartupWithData, investor: InvestorWithThesis) {
    const match = matchEngine.score(startup, investor);
    const extras: string[] = [];
    if (startup.stage === "Pre-Seed" || startup.stage === "Seed") {
      extras.push("Early-stage revenue base — durability of retention is unproven");
    }
    if (startup.tags.some((t) => t.toLowerCase().includes("marketplace"))) {
      extras.push("Marketplace supply concentration should be verified before term sheet");
    }
    return wrap([...match.risks, ...extras].slice(0, 5), this);
  }
}

let provider: InsightProvider = new DeterministicInsightProvider();

/** Swap in a model-backed provider (e.g. a server function calling an LLM). */
export function registerInsightProvider(next: InsightProvider) {
  provider = next;
}

export function insights(): InsightProvider {
  return provider;
}

export const AI_MODE_LABEL =
  "Generated by FundMatch's deterministic demo engine — no external model is connected.";
